### ISSUE TITLE
image for create consignment doesn't render properly on client app

### ISSUE THREAD

**Issue by vidz231** [SWP391TeamProject/SE1840_SWP391_G2#270]
![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/115398831/eac8de30-511b-40bc-8cff-e3d7b42c5907)

**Comment by cuongvt19** [comment]
hình này ở máy anh hiện bình thường

**Comment by vidz231** [comment]
https://www.biddify.fun/create-consignment

trên deployment thì no trắngboc a oi chac do chua đổi cách import ảnh

**Comment by vidz231** [comment]
@cuongvt19
