### ISSUE TITLE
pagination overflow when there is too many page

### ISSUE THREAD

**Issue by vidz231** [SWP391TeamProject/SE1840_SWP391_G2#271]
![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/115398831/0109049c-9c34-4c80-88ea-f061a616334c)

**Comment by vidz231** [comment]
![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/115398831/630047ce-6369-438c-b87e-33cd93c3f207)
still stretching make it have the input field in the meiddle and fixed width

**Comment by cuongvt19** [comment]
what do you mean?

**Comment by cuongvt19** [comment]
@vidz231

**Comment by vidz231** [comment]
kiểu cái này cho nó nếu có nhiều hơn 7 ô page thì cho phần chính giữa hiện ra text field để usser input đc ko a cho nó fixx cứng width luôn

**Comment by vidz231** [comment]
@cuongvt19
