### ISSUE TITLE
kéo thả/ chọn từng ảnh vô DropZone chỉ nhận ảnh cuối cùng 

### ISSUE THREAD

**Issue by phucvjp** [SWP391TeamProject/SE1840_SWP391_G2#278]
kéo thả ảnh từ ngoài vô dropzone để tải ảnh lên server mặc dù hiện đủ những ảnh đó ở dropzone nhưng khi up lên chỉ nhận ảnh cuối cùng.
Tương tự với cách chọn từng ảnh trong máy.
(chọn nhiều ảnh cùng 1 lần thì bình thường, chọn 1 ảnh 1 lần thì chỉ lấy lần cuối)

![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/169065491/a2f33e82-b37c-4e19-8321-3865835fe709)

**Comment by vidz231** [comment]
solved
