### ISSUE TITLE
doc title stuck at Consignment | Biddify after clicking create consignment

### ISSUE THREAD

**Issue by vidz231** [SWP391TeamProject/SE1840_SWP391_G2#292]
![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/115398831/fdd52893-6eb0-4c9d-826a-7720909e2941)

**Comment by cuongvt19** [comment]
> ![image](https://private-user-images.githubusercontent.com/115398831/342011568-fdd52893-6eb0-4c9d-826a-7720909e2941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Mzc5NjQsIm5iZiI6MTcxOTQzNzY2NCwicGF0aCI6Ii8xMTUzOTg4MzEvMzQyMDExNTY4LWZkZDUyODkzLTZlYjAtNGM5ZC04MjZhLTc3MjA5MDllMjk0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMTM0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmJmMDc0OTkwNGJkNWFhNzUxOTRmNTQ5OTljMWFhMTViMTAxYmRmM2VjYTg1OTE1Y2U1ODBkMDNkNzRmZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z7IU2944TepJRJ_yMP-dzFTgjigePrdF1hN2QioUM5w)

chưa hiểu cái issue này lắm

**Comment by cuongvt19** [comment]
@vidz231

**Comment by vidz231** [comment]
cái này kiểu bấm vô cái https://www.biddify.fun/create-consignment này thì title của pagge nó ra title như trên issuexong từ đó bấm mấy cái khác nó vẫn vậy luôn ko quay về biddify nữa

**Comment by vidz231** [comment]
@cuongvt19
