### ISSUE TITLE
Add detail for consignment process

### ISSUE THREAD

**Issue by anhhd45** [SWP391TeamProject/SE1840_SWP391_G2#310]
![Screenshot 2024-06-24 115250](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/143704010/89d935db-3e57-48be-a899-7db55f6b7c3e)

**Comment by cuongvt19** [comment]
thêm những detail gì?

**Comment by cuongvt19** [comment]
@anhhd45

**Comment by anhhd45** [comment]
> @anhhd45

Sửa lại padding, chắc sửa text lại cho đúng consignment process :v

**Comment by cuongvt19** [comment]
> > @anhhd45
> 
> Sửa lại padding, chắc sửa text lại cho đúng consignment process :v

cho a cái process luôn đi :v

**Comment by anhhd45** [comment]
> > > @anhhd45
> > 
> > 
> > Sửa lại padding, chắc sửa text lại cho đúng consignment process :v
> 
> cho a cái process luôn đi :v

để mai tính đi a :v chắc cái này chỉ cần để cái ảnh thôi
@vidz231 
@vidz231 
@vidz231 
@vidz231

**Comment by vidz231** [comment]
@cuongvt19 cai nay low priority chuan can  dau...

**Comment by vidz231** [comment]
này cho tạm một ô check 2fa authentication đi a cho mấy cái box á @cuongvt19  còn mấy cái ô còn lại đẻ trống đi nào có idea thêm sau với layout lại nhìn chuẫn chỉ tý còn phần đàu trang đó cho cái text welcome user đi a @cuongvt19
