### ISSUE TITLE
Auction session pagination và status filter chưa working

### ISSUE THREAD

**Issue by anhhd45** [SWP391TeamProject/SE1840_SWP391_G2#350]
- Bug: loading lâu nên pagination chưa hiện kịp, có thể nhấn nhiều lần
- Nên cho chuyển pagination trước và hiện loading

**Comment by cuongvt19** [comment]
@anhhd45 @vidz231 giải thích rõ hơn cho a với, là pagin lên trc mà list trc hiện hay sao?

**Comment by anhhd45** [comment]
> @anhhd45 @vidz231 giải thích rõ hơn cho a với, là pagin lên trc mà list trc hiện hay sao?

Lúc chuyển trang thì nó fetch từ server, nhưng mà cái khung thì chưa có loading, và ở thanh pagination thì vẫn hiện trang hiện tại; cho đến khi fetch xong mới update pagination :v 
nên e nghĩ là nên thêm loading, cập nhật pagination qua trang mới, rồi khóa pagination lại cho đến khi fetch xong, hoặc có error mới được dùng :v
