### ISSUE TITLE
Auction session chưa cho chọn time, lỗi status trong detail

### ISSUE THREAD

**Issue by anhhd45** [SWP391TeamProject/SE1840_SWP391_G2#351]
- Cho chọn cụ thể time http://localhost:5173/admin/auction-sessions/create
   + Tham khảo, giống trong trang detail http://localhost:5173/admin/auction-sessions/1
- Hiện thời gian ở ngoài auction list http://localhost:5173/admin/auction-sessions/
- Xóa nút edit
- Trong detail, nút select chưa hiện status hiện tại: http://localhost:5173/admin/auction-sessions/1

**Comment by vidz231** [comment]
hien thoi gian la ko can thiet start date vs end date la du~ r con time vo detail coi hop ly hon
