### ISSUE TITLE
Fix account disabled

### ISSUE THREAD

**Issue by anhhd45** [SWP391TeamProject/SE1840_SWP391_G2#360]
Đổi disable thành deactivate

**Comment by vidz231** [comment]
where ??? @anhhd45

**Comment by vidz231** [comment]
why tho it basically have the same meaning...
![image](https://github.com/SWP391TeamProject/SE1840_SWP391_G2/assets/115398831/0228543a-ec46-4e77-afcd-df09692b0fc0)
